"""Build Mexican Spanish survival phrase pack."""
import json
from pathlib import Path

entries = [
    # ============================================================
    # MEXICANISMOS WITH TRAPS (~50)
    # ============================================================
    {"category": "mexicanismos", "english_context": "[someone asks when you'll do something — you mean 'in a bit, not now, vaguely soon'] response", "spanish": "Ahorita.", "note": "TRAP: 'ahorita' almost never means 'right now' in Mexico. Closer to 'in a while / eventually / maybe soon'. Could be 5 min or 5 hours."},
    {"category": "mexicanismos", "english_context": "[you actually mean immediately, this instant — emphasizing] response", "spanish": "Ahoritita / ahorita mismo.", "note": "Diminutive of the diminutive, OR add 'mismo'. Plain 'ahorita' is too vague to mean 'now'."},
    {"category": "mexicanismos", "english_context": "[someone calls your name — you respond like a Mexican, not 'qué?'] response", "spanish": "¿Mande?", "note": "Standard polite Mexican response when called. '¿Qué?' sounds rude here. Also used to ask 'what did you say?' Still common with all ages, slightly less among young urban speakers but never wrong."},
    {"category": "mexicanismos", "english_context": "[you didn't catch what someone said, polite] response", "spanish": "¿Mande usted?", "note": "More formal version. With strangers/elders default to this."},
    {"category": "mexicanismos", "english_context": "[agreeing enthusiastically — 'go for it / let's do it / right on'] response", "spanish": "¡Órale!", "note": "Multipurpose: agreement, surprise, encouragement, 'wow'. Tone disambiguates."},
    {"category": "mexicanismos", "english_context": "[confirming a plan casually — 'cool, deal, sounds good'] response", "spanish": "Sale.", "note": "Very Mexican confirmation. 'Sale y vale' is emphatic. Use after agreeing on plans."},
    {"category": "mexicanismos", "english_context": "[short 'okay/sure' — confirming you'll do something] response", "spanish": "Va.", "note": "Even more clipped than 'sale'. Casual, among friends."},
    {"category": "mexicanismos", "english_context": "[encouraging someone to do something — 'go on, hurry up, c'mon'] response", "spanish": "¡Ándale!", "note": "Encouragement, urging, also confirmation ('that's right!'). Stress on first syllable: ÁN-da-le."},
    {"category": "mexicanismos", "english_context": "[friendly farewell-ish 'okay then, alright'] response", "spanish": "Ándale pues.", "note": "Soft wrap-up phrase. Often before hanging up or parting."},
    {"category": "mexicanismos", "english_context": "[saying something is awesome — Mexican, NOT 'genial' or 'guay'] response", "spanish": "¡Qué chido!", "note": "'Chido' = cool/awesome. Distinctively Mexican. 'Guay' is Spanish from Spain — don't use it."},
    {"category": "mexicanismos", "english_context": "[saying something is cool — alternative to 'chido', equally Mexican] response", "spanish": "¡Qué padre!", "note": "Same meaning as 'chido'. 'Está padrísimo' = it's awesome. Has nothing to do with father here."},
    {"category": "mexicanismos", "english_context": "[addressing a male friend casually — 'dude, man, bro'] response", "spanish": "¿Qué onda, güey?", "note": "Pronounced 'wey'. Spelled 'wey' or 'güey'. ONLY among friends — calling a stranger güey is aggressive. Overuse marks you as faking it."},
    {"category": "mexicanismos", "english_context": "[greeting a friend — 'what's up?'] response", "spanish": "¿Qué onda?", "note": "Standard casual Mexican greeting among peers. Equivalent of 'what's up'."},
    {"category": "mexicanismos", "english_context": "[expressing disbelief — 'no way! / are you serious?'] response", "spanish": "¡No manches!", "note": "Polite-ish version of '¡no mames!'. Safe in mixed company. Means 'don't mess with me / no way'."},
    {"category": "mexicanismos", "english_context": "[stronger 'no way!' — vulgar, only with close friends] response", "spanish": "¡No mames!", "note": "VULGAR. Literally crude. Only with close friends, never with strangers/elders/work."},
    {"category": "mexicanismos", "english_context": "[asking 'really? for real?'] response", "spanish": "¿Neta?", "note": "'Neta' = truth/real. '¿Es neta?' = 'are you serious?'. 'La neta' = 'the truth/honestly'."},
    {"category": "mexicanismos", "english_context": "[introducing your honest opinion — 'honestly...'] response", "spanish": "La neta...", "note": "Like 'tbh / honestly'. La neta es que no quiero ir = honestly I don't want to go."},
    {"category": "mexicanismos", "english_context": "[ordering 'a little coffee' — Mexican diminutive habit] response", "spanish": "Un cafecito, por favor.", "note": "Mexicans diminutize constantly. Doesn't mean small — softens/warms the request. Use the -ito/-ita form by default in service interactions."},
    {"category": "mexicanismos", "english_context": "[asking for 'just a little bit' of something] response", "spanish": "Tantito, por favor.", "note": "'Tantito' = a little bit. 'Espérame tantito' = wait a sec. Distinctively Mexican."},
    {"category": "mexicanismos", "english_context": "[asking someone to wait a sec] response", "spanish": "Espérame tantito.", "note": "Standard Mexican 'hold on a sec'."},
    {"category": "mexicanismos", "english_context": "[expressing 'damn / wow / yikes'] response", "spanish": "¡Híjole!", "note": "Mild interjection — surprise, dismay, sympathy. Totally safe register. Euphemism for 'hijo de...'."},
    {"category": "mexicanismos", "english_context": "[expressing surprise/shock — 'whoa! / shoot!'] response", "spanish": "¡Chale!", "note": "Disappointment or mild dismay. 'Ah chale, se canceló' = 'aw man, it got cancelled'."},
    {"category": "mexicanismos", "english_context": "[saying 'no way / nah / c'mon man' — disagreeing with skepticism] response", "spanish": "N'ombre.", "note": "Contraction of 'no, hombre'. Pronounced 'nom-bre'. Strong skeptical 'nah'."},
    {"category": "mexicanismos", "english_context": "[saying you like the sound of a plan — 'I'm into it / sounds good'] response", "spanish": "Me late.", "note": "Mexican for 'I dig it / I'm down'. Literally 'it beats to me' (heart). 'Me late la idea' = I like the idea."},
    {"category": "mexicanismos", "english_context": "[asking 'what's going on / what's the deal?'] response", "spanish": "¿Qué pedo?", "note": "VULGAR but extremely common among male friends. Means 'what's up'. Don't use with strangers/work/elders."},
    {"category": "mexicanismos", "english_context": "[saying someone's drunk] response", "spanish": "Está bien pedo.", "note": "'Pedo' literally = fart, but in Mexican slang = drunk OR problem ('no hay pedo' = no problem). VULGAR."},
    {"category": "mexicanismos", "english_context": "[reassuring someone — 'no worries, no problem'] response", "spanish": "No hay pedo.", "note": "VULGAR-ish but very common among friends. Polite version: 'no hay bronca' or 'no hay problema'."},
    {"category": "mexicanismos", "english_context": "[polite 'no problem / no worries'] response", "spanish": "No hay bronca.", "note": "'Bronca' = trouble/fight. Safer than 'no hay pedo'."},
    {"category": "mexicanismos", "english_context": "[intensifier — 'damn / freaking', mild profanity] response", "spanish": "Pinche...", "note": "Mexican 'damn/freaking'. 'Pinche frío' = damn cold. Mild but still profanity — fine with friends, not at work/with elders. Always before the noun."},
    {"category": "mexicanismos", "english_context": "[saying it's super cold — using Mexican intensifier] response", "spanish": "Hace un pinche frío.", "note": "Pinche+noun is the standard Mexican intensifier construction."},
    {"category": "mexicanismos", "english_context": "[saying something/someone is awesome — 'a toda madre'] response", "spanish": "Está a toda madre.", "note": "'A toda madre' = great/awesome. Despite 'madre', not offensive — but informal. Opposite: 'de poca madre' actually ALSO means great. Mexican Spanish has many 'madre' expressions of opposite meanings."},
    {"category": "mexicanismos", "english_context": "[saying something is awful / went badly] response", "spanish": "Me fue de la chingada.", "note": "VULGAR. 'De la chingada' = terribly. 'Chingar' family is the most loaded verb in Mexican Spanish — read Octavio Paz on it. Use cautiously."},
    {"category": "mexicanismos", "english_context": "[telling someone to go away — vulgar but common] response", "spanish": "Vete a la chingada.", "note": "VULGAR. Equivalent to 'f*** off'. Know it to recognize it; don't deploy it."},
    {"category": "mexicanismos", "english_context": "[saying you don't care at all] response", "spanish": "Me vale madre.", "note": "VULGAR-ish. 'Me vale' alone is softer ('I don't care'). Adding 'madre' intensifies."},
    {"category": "mexicanismos", "english_context": "[saying 'whatever / I don't care' — softer version] response", "spanish": "Me da igual.", "note": "Pan-Hispanic, safe in any register. Use this with strangers/work."},
    {"category": "mexicanismos", "english_context": "[describing something easy — 'piece of cake'] response", "spanish": "Está pan comido.", "note": "Common Mexican idiom for 'super easy'."},
    {"category": "mexicanismos", "english_context": "[asking 'what's wrong / what happened?' to someone visibly off] response", "spanish": "¿Qué te pasó?", "note": "Standard. 'Qué onda contigo' is the casual friend version."},
    {"category": "mexicanismos", "english_context": "[playful 'hey, what's with you?' to a friend acting weird] response", "spanish": "¿Qué onda contigo?", "note": "Friendly call-out among peers."},
    {"category": "mexicanismos", "english_context": "[asking 'now what?' or 'what should I do?'] response", "spanish": "¿Y ora?", "note": "Contraction of 'y ahora'. Very Mexican. Confused/exasperated."},
    {"category": "mexicanismos", "english_context": "[saying 'I'm broke / no money'] response", "spanish": "Ando bien bruja.", "note": "'Andar bruja' = broke. 'Ando sin lana' is also good. 'Lana' = money."},
    {"category": "mexicanismos", "english_context": "[the slang word for 'money' in Mexico] response", "spanish": "Lana.", "note": "'Lana' (lit. wool) = money. 'No traigo lana' = I don't have cash. Also 'varo' = peso/buck."},
    {"category": "mexicanismos", "english_context": "[asking 'do you have a few bucks?'] response", "spanish": "¿Traes unos varos?", "note": "'Varo' = peso, casually 'buck'. Friend register."},
    {"category": "mexicanismos", "english_context": "[describing a party / fun event — 'it was a blast'] response", "spanish": "Estuvo bien chido.", "note": "'Bien' as intensifier (= 'really') is very Mexican. 'Bien rico, bien padre, bien chido.'"},
    {"category": "mexicanismos", "english_context": "[expressing reluctance / laziness — 'I can't be bothered'] response", "spanish": "Me da hueva.", "note": "'Hueva' = laziness/can't-be-bothered. 'Qué hueva' = ugh, what a drag. Mildly crude."},
    {"category": "mexicanismos", "english_context": "[describing a lazy person] response", "spanish": "Es bien huevón.", "note": "'Huevón' = lazy. Mildly crude. 'Flojo' is the polite version."},
    {"category": "mexicanismos", "english_context": "[saying 'I'm starving'] response", "spanish": "Traigo un hambre...", "note": "'Traigo hambre/sueño/frío' is a Mexicanism for 'I'm hungry/sleepy/cold' instead of 'tengo'. Both work."},
    {"category": "mexicanismos", "english_context": "[friend leaving — casual goodbye, 'take care, see you'] response", "spanish": "Bye, cuídate.", "note": "English 'bye' is fully naturalized in CDMX. Often 'bai'. 'Cuídate' is the warm sign-off."},
    {"category": "mexicanismos", "english_context": "[saying something is super expensive] response", "spanish": "Está carísimo / un dineral.", "note": "'Un dineral' = a fortune. '-ísimo' superlatives are everywhere."},
    {"category": "mexicanismos", "english_context": "[describing a hassle / annoying situation] response", "spanish": "Qué rollo.", "note": "'Rollo' = whole thing/situation/hassle. '¿Cuál es el rollo?' = what's the deal?"},
    {"category": "mexicanismos", "english_context": "[a lie / made-up story] response", "spanish": "Puro choro.", "note": "'Choro' = BS / empty talk. 'Echar choro' = to ramble/BS."},
    {"category": "mexicanismos", "english_context": "[saying something/someone is annoying] response", "spanish": "Qué mala onda.", "note": "'Mala onda' = bad vibes / uncool. 'Eres bien mala onda' = you're being uncool."},
    {"category": "mexicanismos", "english_context": "[saying someone is cool/nice] response", "spanish": "Es buena onda.", "note": "Opposite of mala onda. Common compliment."},

    # ============================================================
    # RESTAURANTS & TAQUERÍAS (~40)
    # ============================================================
    {"category": "restaurants", "english_context": "[at a taco stand] ordering two al pastor tacos with everything] response", "spanish": "Dos de pastor con todo, por favor.", "note": "'De pastor' (not 'de tacos al pastor'). 'Con todo' = onion + cilantro + salsa. Standard taquería shorthand."},
    {"category": "restaurants", "english_context": "[taco stand] one al pastor without onion] response", "spanish": "Uno de pastor sin cebolla.", "note": "Cilantro and onion are the default toppings — specify what to omit."},
    {"category": "restaurants", "english_context": "[taco stand] without cilantro] response", "spanish": "Sin cilantro, por favor.", "note": "Common request from foreigners who get the soap-gene cilantro experience."},
    {"category": "restaurants", "english_context": "[taco stand] asking for an order to go] response", "spanish": "Para llevar, por favor.", "note": "Standard. Opposite: 'para aquí' / 'para comer aquí'."},
    {"category": "restaurants", "english_context": "[taco stand] eating in] response", "spanish": "Para aquí.", "note": "Or 'para comer aquí'. Pan-Hispanic 'para llevar/aquí'."},
    {"category": "restaurants", "english_context": "[taco stand] asking what they recommend] response", "spanish": "¿Qué me recomienda?", "note": "Usted form — proper for service. Tú: '¿qué me recomiendas?'"},
    {"category": "restaurants", "english_context": "[taco stand] asking if a salsa is spicy] response", "spanish": "¿Está picante?", "note": "Crucial question. Mexican 'no pica' can still be hot for foreigners. Ask which is mildest: '¿cuál es la menos picante?'"},
    {"category": "restaurants", "english_context": "[asking which salsa is least spicy] response", "spanish": "¿Cuál es la menos picosa?", "note": "'Picoso/picosa' is more common in Mexico than 'picante'."},
    {"category": "restaurants", "english_context": "[restaurant] asking for the check] response", "spanish": "La cuenta, por favor.", "note": "Or 'me trae la cuenta'. Air-scribbling gesture works too. Mexican waiters generally won't bring the check until asked."},
    {"category": "restaurants", "english_context": "[asking if they take card] response", "spanish": "¿Aceptan tarjeta?", "note": "Cash still rules at street stalls. Many small places: 'solo efectivo'."},
    {"category": "restaurants", "english_context": "[only cash — what you'll hear] response", "spanish": "Solo efectivo.", "note": "Recognize this. 'Efectivo' = cash."},
    {"category": "restaurants", "english_context": "[saying you want it spicy] response", "spanish": "Échele salsa, por favor.", "note": "'Echar' = to put on/add. Very common verb at food stalls."},
    {"category": "restaurants", "english_context": "[asking for extra tortillas] response", "spanish": "¿Me regala unas tortillas más?", "note": "'Me regala' literally 'gift me' but in Mexico = polite 'could you give me'. Used constantly in service contexts. NOT actually asking for a gift."},
    {"category": "restaurants", "english_context": "[ordering — 'could I have a coke please' using the polite Mexican formula] response", "spanish": "¿Me regala una Coca, por favor?", "note": "'Me regala' is the Mexican polite ordering frame. More common than 'me da' for asking."},
    {"category": "restaurants", "english_context": "[taco type — slow-cooked beef from the pot] gloss", "spanish": "Suadero", "note": "Cut from beef brisket/flank, cooked in its own fat. Taquería staple. Pronounced 'suah-DEH-roh'."},
    {"category": "restaurants", "english_context": "[taco type — beef tongue] gloss", "spanish": "Lengua", "note": "Tongue. Tender, mild, beloved by Mexicans. Try it before deciding."},
    {"category": "restaurants", "english_context": "[taco type — tripe, crispy fried] gloss", "spanish": "Tripa", "note": "Beef intestine, fried crispy. Acquired taste. Often paired with suadero."},
    {"category": "restaurants", "english_context": "[taco type — mix of meats, often pastor + suadero + chorizo] gloss", "spanish": "Campechano", "note": "Mixed meats. Different stands mix differently — usually pastor + something."},
    {"category": "restaurants", "english_context": "[taco wrapped in flour tortilla with melted cheese, pastor] gloss", "spanish": "Gringa", "note": "Flour tortilla + cheese + al pastor + folded/grilled like a quesadilla. Despite the name, fully authentic Mexican."},
    {"category": "restaurants", "english_context": "[taco type — pork carnitas, slow-fried pork] gloss", "spanish": "Carnitas", "note": "Slow-cooked confit-style pork, shredded. Michoacán specialty, available everywhere."},
    {"category": "restaurants", "english_context": "[taco type — pork in adobo sauce on vertical spit] gloss", "spanish": "Al pastor", "note": "Marinated pork on trompo (vertical spit), shaved off with a slice of pineapple. Mexico City emblematic."},
    {"category": "restaurants", "english_context": "[stuffed flat masa cake, Mexican street food] gloss", "spanish": "Tlacoyo / huarache / sope", "note": "Different masa-based bases topped with beans/cheese/meat. Worth trying — distinctively Mexican beyond tacos."},
    {"category": "restaurants", "english_context": "[asking for it 'with everything on it'] response", "spanish": "Con todo.", "note": "Default toppings for whatever you're ordering. Simplest shortcut."},
    {"category": "restaurants", "english_context": "[asking for it without beans] response", "spanish": "Sin frijoles.", "note": "Beans appear by default in many dishes."},
    {"category": "restaurants", "english_context": "[asking for limes] response", "spanish": "¿Me trae unos limones?", "note": "TRAP: in Mexico 'limón' = lime (the green one). 'Lima' is something else (sweet lime). Limes are everywhere — always asked for."},
    {"category": "restaurants", "english_context": "[asking 'what's in this dish?'] response", "spanish": "¿Qué lleva este platillo?", "note": "'Lleva' = contains/carries. 'Platillo' = dish (meal sense), not 'plato' (the actual plate)."},
    {"category": "restaurants", "english_context": "[saying you don't eat meat] response", "spanish": "No como carne.", "note": "Vegetarianism is uncommon in everyday Mexican food culture. May need to explain. 'Soy vegetariano/a'."},
    {"category": "restaurants", "english_context": "[asking if a dish has meat — vegetarian check] response", "spanish": "¿Tiene carne? Soy vegetariano.", "note": "'Sin carne' may still come with chicken/fish in some places — chicken is often considered separate from 'carne'. Specify."},
    {"category": "restaurants", "english_context": "[checking if soup or beans were made with lard] response", "spanish": "¿Lleva manteca?", "note": "'Manteca' = lard. Beans/tamales often made with it — vegetarian gotcha."},
    {"category": "restaurants", "english_context": "[asking for the bill to be split] response", "spanish": "¿Nos divide la cuenta?", "note": "'Dividir la cuenta' or 'cuentas separadas'. Less expected than in US — many restaurants resist."},
    {"category": "restaurants", "english_context": "[tip is included? asking] response", "spanish": "¿La propina está incluida?", "note": "'Propina' = tip. Usually NOT included in Mexico. 10-15% standard at sit-down restaurants. Street stalls: not expected."},
    {"category": "restaurants", "english_context": "[leaving 15% tip — telling waiter to add it to card] response", "spanish": "Agréguele el quince, por favor.", "note": "Standard at sit-down. They'll punch in the tip on the card terminal in front of you."},
    {"category": "restaurants", "english_context": "[asking for water — bottled, since tap is risky] response", "spanish": "Una botella de agua, por favor.", "note": "Specify bottled. 'Agua natural' (still) vs 'agua mineral' (sparkling). 'Natural' does NOT mean 'tap'."},
    {"category": "restaurants", "english_context": "[ordering still water] response", "spanish": "Agua natural.", "note": "TRAP: 'natural' = still/non-carbonated, not 'tap'. Bottled by default in restaurants."},
    {"category": "restaurants", "english_context": "[ordering sparkling water] response", "spanish": "Agua mineral.", "note": "Carbonated. 'Con gas' also understood."},
    {"category": "restaurants", "english_context": "[asking for an agua fresca flavor] response", "spanish": "¿De qué son las aguas?", "note": "Standard question at lunch counters. Aguas frescas (jamaica, horchata, tamarindo, limón) usually 2-3 flavors of the day."},
    {"category": "restaurants", "english_context": "[hibiscus iced tea — common agua fresca] gloss", "spanish": "Agua de jamaica", "note": "Pronounced 'ha-MAI-ka'. Tart, red. Default safe choice."},
    {"category": "restaurants", "english_context": "[ordering the lunch special / set menu] response", "spanish": "El menú del día / la comida corrida.", "note": "'Comida corrida' = fixed lunch menu, usually 3 courses for ~$80-150 MXN. Best value, most authentic."},
    {"category": "restaurants", "english_context": "[saying you're done / take the plate] response", "spanish": "Ya terminé, gracias.", "note": "Standard. Mexican waiters won't clear unless you signal."},
    {"category": "restaurants", "english_context": "[saying it was delicious] response", "spanish": "Estuvo riquísimo.", "note": "'Rico' is the food compliment in Mexico, not 'delicioso'. '-ísimo' superlative is the move."},
    {"category": "restaurants", "english_context": "[asking for to-go boxes for leftovers] response", "spanish": "¿Me lo pone para llevar?", "note": "'Para llevar' covers takeout AND leftovers."},

    # ============================================================
    # TAXIS, UBER, TRANSPORT (~30)
    # ============================================================
    {"category": "transport", "english_context": "[hailing a taxi] checking it's available] response", "spanish": "¿Está libre?", "note": "Standard. Many CDMX taxis have a 'LIBRE' sign in the windshield."},
    {"category": "transport", "english_context": "[asking the fare to a destination before getting in] response", "spanish": "¿Cuánto me cobra hasta la Roma?", "note": "ALWAYS ask first if not metered. CDMX street taxis often negotiate. Uber/DiDi safer for tourists."},
    {"category": "transport", "english_context": "[asking if they use the meter] response", "spanish": "¿Usa taxímetro?", "note": "Legitimate CDMX taxis should. Many won't with tourists. Insist or use Uber."},
    {"category": "transport", "english_context": "[directing the driver — 'drop me here'] response", "spanish": "Aquí me deja, por favor.", "note": "'Me deja' = leave me. Standard."},
    {"category": "transport", "english_context": "[asking to be let off at the next corner] response", "spanish": "En la próxima esquina, por favor.", "note": "Useful when you spot your destination."},
    {"category": "transport", "english_context": "[asking driver to pull over up ahead] response", "spanish": "Más adelante, por favor.", "note": "'Adelante' = ahead. 'Más adelante' = a bit further."},
    {"category": "transport", "english_context": "[telling driver to stop here] response", "spanish": "Aquí está bien.", "note": "Polite signal to stop. Then 'me deja aquí'."},
    {"category": "transport", "english_context": "[asking driver to wait a moment] response", "spanish": "¿Me espera tantito?", "note": "'Tantito' Mexicanism softens it. Useful at ATM stops."},
    {"category": "transport", "english_context": "[Uber pin is wrong — telling driver actual location] response", "spanish": "Estoy en la entrada de... / mejor véngame por...", "note": "Common Uber issue. Be ready with a clear landmark."},
    {"category": "transport", "english_context": "[CDMX subway] generic name] response", "spanish": "El metro.", "note": "CDMX Metro is cheap (~$5 MXN/ride), extensive, but very crowded. Watch belongings. Women-only cars at front during rush."},
    {"category": "transport", "english_context": "[CDMX bus rapid transit — dedicated lane buses] gloss", "spanish": "El Metrobús.", "note": "CDMX BRT system. Same fare card as Metro. Less crowded than metro on some lines."},
    {"category": "transport", "english_context": "[small minibus / shared van — local CDMX transport] gloss", "spanish": "Pesero / combi / micro.", "note": "Cheap colectivo-style buses. Flag down anywhere on route. 'Micro' or 'pesero' in CDMX. Tell driver 'bajan' to get off."},
    {"category": "transport", "english_context": "[telling pesero/micro driver you want off] response", "spanish": "¡Bajan!", "note": "Shouted toward the driver. Literally 'getting off!'. Standard signal on Mexican local buses."},
    {"category": "transport", "english_context": "[asking how much the bus fare is] response", "spanish": "¿Cuánto es el pasaje?", "note": "'Pasaje' = fare. Pesero fares vary by distance — pay the driver as you board."},
    {"category": "transport", "english_context": "[Metro fare card] gloss", "spanish": "La tarjeta del metro / MI Movilidad.", "note": "Rechargeable card for Metro/Metrobús/Trolebús. Buy at any station."},
    {"category": "transport", "english_context": "[asking 'is this stop the one for X?'] response", "spanish": "¿Esta parada es para...?", "note": "On bus/metro. 'Parada' = stop. 'Estación' = station."},
    {"category": "transport", "english_context": "[asking which line goes to a destination in the metro] response", "spanish": "¿Qué línea va a Coyoacán?", "note": "Line numbers/colors. Useful at info booths in big stations."},
    {"category": "transport", "english_context": "[asking where to transfer] response", "spanish": "¿Dónde hago transbordo?", "note": "'Transbordo' = transfer. Or 'correspondencia'."},
    {"category": "transport", "english_context": "[asking for directions on the street] response", "spanish": "Disculpe, ¿cómo llego a...?", "note": "'Disculpe' (not 'perdón') opens the question politely."},
    {"category": "transport", "english_context": "[asking if it's far / walking distance] response", "spanish": "¿Está lejos? ¿Se puede caminar?", "note": "Useful sanity check before committing."},
    {"category": "transport", "english_context": "[asking 'how many blocks?'] response", "spanish": "¿A cuántas cuadras?", "note": "'Cuadra' = block. Mexican standard unit of urban distance."},
    {"category": "transport", "english_context": "[saying you got lost] response", "spanish": "Me perdí, ¿me orienta?", "note": "'Me orienta' = could you point me. Polite ask for help when disoriented."},
    {"category": "transport", "english_context": "[asking driver if he knows how to get there] response", "spanish": "¿Sabe llegar?", "note": "Casual but normal. Some drivers don't — better to know now."},
    {"category": "transport", "english_context": "[at airport — asking for the official taxi stand] response", "spanish": "¿Dónde están los taxis autorizados?", "note": "CRITICAL at MEX airport. Pre-pay at official kiosk inside terminal. Don't accept rides from people approaching you."},
    {"category": "transport", "english_context": "[Uber pickup confirmation — 'I'm the passenger / are you for Ian?'] response", "spanish": "¿Es usted para Ian?", "note": "Uber driver may not get out. Confirm name before getting in."},
    {"category": "transport", "english_context": "[asking driver to use a specific route] response", "spanish": "¿Podemos ir por Reforma?", "note": "Useful in CDMX where traffic varies wildly by route."},
    {"category": "transport", "english_context": "[traffic is bad — empathetic comment to driver] response", "spanish": "Está pesado el tráfico, ¿no?", "note": "Small talk move. 'Está pesado' = it's heavy/bad. Mexican drivers will agree at length."},
    {"category": "transport", "english_context": "[asking for change for a 200-peso bill at a taxi] response", "spanish": "¿Tiene cambio de doscientos?", "note": "ALWAYS check before the ride if you only have big bills. Many won't."},
    {"category": "transport", "english_context": "[telling a tout 'no thanks' firmly but politely] response", "spanish": "No, gracias. Estoy bien.", "note": "Repeat as needed. 'Estoy bien' is the polite shutdown."},
    {"category": "transport", "english_context": "[asking how to get to the bus terminal] response", "spanish": "¿Cómo llego a la central de autobuses?", "note": "CDMX has 4 main terminals (Norte, Sur, Oriente/TAPO, Poniente). Specify which: 'la del Norte', etc."},

    # ============================================================
    # MARKET / SHOPPING / HAGGLING (~25)
    # ============================================================
    {"category": "shopping", "english_context": "[market] asking the price] response", "spanish": "¿Cuánto cuesta?", "note": "Or '¿a cómo?' which is more market-typical. '¿A cómo el kilo?' = how much per kilo?"},
    {"category": "shopping", "english_context": "[market] asking 'how much per kilo?'] response", "spanish": "¿A cómo el kilo?", "note": "Distinctively market/street vendor phrasing. Pricing in metric — kilo, medio kilo, cuarto kilo."},
    {"category": "shopping", "english_context": "[market] asking for a discount] response", "spanish": "¿Me hace un descuento?", "note": "Markets and tianguis: yes. Established stores: no. Crafts/souvenirs in tourist areas: yes, expected."},
    {"category": "shopping", "english_context": "[saying it's too expensive — opening a haggle] response", "spanish": "Está muy caro.", "note": "Standard opener. Vendor will counter. Don't insult — it's a dance, not a fight."},
    {"category": "shopping", "english_context": "[asking the final/best price] response", "spanish": "¿Qué es lo último?", "note": "'Lo último' = the last/final price. Critical haggling phrase. Means 'cut to your real bottom line'."},
    {"category": "shopping", "english_context": "[asking them to hold an item for you while you keep shopping] response", "spanish": "¿Me lo guarda?", "note": "Vendors will hold items for you to come back. Useful at markets."},
    {"category": "shopping", "english_context": "[deciding to buy it — 'I'll take it'] response", "spanish": "Me lo llevo.", "note": "Closes the deal. After negotiating."},
    {"category": "shopping", "english_context": "[asking for half a kilo] response", "spanish": "Medio kilo, por favor.", "note": "Common produce unit. 'Cuarto' = quarter kilo."},
    {"category": "shopping", "english_context": "[asking for a quarter kilo] response", "spanish": "Un cuarto, por favor.", "note": "Implied 'de kilo'. Standard at deli/cheese counters."},
    {"category": "shopping", "english_context": "[asking for one piece / one unit] response", "spanish": "Una pieza.", "note": "For things sold by the piece (fruit, bread). 'Una pieza de pan'."},
    {"category": "shopping", "english_context": "[asking 'do you have...?'] response", "spanish": "¿Tiene...?", "note": "Or '¿maneja...?' in stores: '¿maneja tallas grandes?' (do you carry big sizes?)."},
    {"category": "shopping", "english_context": "[asking 'can I try it on?'] response", "spanish": "¿Me lo puedo probar?", "note": "'Probar' = try on (clothes) or taste (food). '¿Dónde están los probadores?' = fitting rooms?"},
    {"category": "shopping", "english_context": "[asking 'do you have it in another color/size?'] response", "spanish": "¿Lo tiene en otro color / otra talla?", "note": "'Talla' for clothes, 'número' for shoes."},
    {"category": "shopping", "english_context": "[saying 'I'm just looking, thanks'] response", "spanish": "Solo estoy viendo, gracias.", "note": "Polite shutdown to overeager vendors."},
    {"category": "shopping", "english_context": "[asking 'can I taste it?' at a market] response", "spanish": "¿Lo puedo probar?", "note": "Vendors expect this for fruit, cheese, mole. Common practice."},
    {"category": "shopping", "english_context": "[asking which fruit is ripe / for today] response", "spanish": "¿Cuál está para hoy?", "note": "Useful for mangoes, avocados — vendor will pick the ones to eat today vs in 2-3 days."},
    {"category": "shopping", "english_context": "[asking 'and to take with me for tomorrow?'] response", "spanish": "¿Y para mañana / pasado mañana?", "note": "Continues the previous question. Vendors will sort by ripeness."},
    {"category": "shopping", "english_context": "[asking for it to be wrapped / bagged separately] response", "spanish": "¿Me lo separa, por favor?", "note": "Useful to keep produce/items grouped."},
    {"category": "shopping", "english_context": "[saying you'll think about it — polite no for now] response", "spanish": "Lo pienso y regreso.", "note": "Both sides know you might not. Polite exit from a haggle without commitment."},
    {"category": "shopping", "english_context": "[asking if they have a bag] response", "spanish": "¿Me da una bolsa?", "note": "Many CDMX stores charge for bags now (anti-plastic law). Bring a tote."},
    {"category": "shopping", "english_context": "[asking 'where do I pay?'] response", "spanish": "¿Dónde pago? / ¿Dónde está la caja?", "note": "'Caja' = checkout/register."},
    {"category": "shopping", "english_context": "[asking for a receipt] response", "spanish": "¿Me da el ticket?", "note": "'Ticket' (pronounced 'tee-ket') is fully Mexican Spanish for receipt. 'Recibo' or 'factura' is more formal/for tax purposes."},
    {"category": "shopping", "english_context": "[asking for an itemized tax invoice — for business] response", "spanish": "¿Me hace factura?", "note": "'Factura' = official tax invoice (CFDI). Different from a receipt. Need for business expenses."},
    {"category": "shopping", "english_context": "[saying 'I'll pay in cash'] response", "spanish": "Pago en efectivo.", "note": "'Efectivo' = cash. Often gets a discount at small businesses."},
    {"category": "shopping", "english_context": "[a cluster of stalls / open-air weekly market] gloss", "spanish": "Tianguis.", "note": "Open-air weekly market, neighborhood-based. From Nahuatl. Different days in different neighborhoods. Pronunciation: 'tee-AHN-gees'."},

    # ============================================================
    # POLITENESS / REGISTER (~25)
    # ============================================================
    {"category": "politeness", "english_context": "[squeezing past someone in a crowded space] response", "spanish": "Con permiso.", "note": "Default for moving through space — getting off the metro, passing in a hallway. NOT 'perdón' for this."},
    {"category": "politeness", "english_context": "[response when someone says 'con permiso' to you] response", "spanish": "Propio.", "note": "Underused but very Mexican. Means 'go ahead, you don't need permission'. Older speakers especially. Marks you as someone who knows the country."},
    {"category": "politeness", "english_context": "[bumping into someone, apologizing] response", "spanish": "Perdón / disculpe.", "note": "'Perdón' for apology, 'disculpe' for getting attention. Don't conflate with 'con permiso'."},
    {"category": "politeness", "english_context": "[getting a stranger's attention politely] response", "spanish": "Disculpe...", "note": "Default opener for asking strangers anything. 'Disculpa' (tú) for peers/younger."},
    {"category": "politeness", "english_context": "[good morning — until ~1pm] response", "spanish": "Buenos días.", "note": "Switch to 'tardes' after lunch (~2pm onward). Mexicans take greetings seriously — entering a small shop, greet."},
    {"category": "politeness", "english_context": "[good afternoon — after lunch through evening] response", "spanish": "Buenas tardes.", "note": "Roughly 2pm - dusk. Use even briefly entering a shop/elevator."},
    {"category": "politeness", "english_context": "[good evening / night — after dark] response", "spanish": "Buenas noches.", "note": "Greeting AND farewell at night. Unlike English, you greet someone with 'buenas noches' on arrival."},
    {"category": "politeness", "english_context": "[abbreviated greeting — friendly, time-of-day-flexible] response", "spanish": "Buenas.", "note": "Casual. Gender-marked feminine because implied 'tardes/noches'. Use with peers, in shops."},
    {"category": "politeness", "english_context": "[entering a small shop — greeting the shopkeeper] response", "spanish": "Buenas tardes.", "note": "Mexican CULTURAL norm: ALWAYS greet on entering a shop, elevator, waiting room. Skipping is rude."},
    {"category": "politeness", "english_context": "[greeting a group as you enter a room] response", "spanish": "Buenas tardes a todos.", "note": "Greet the room. Skipping = impolite."},
    {"category": "politeness", "english_context": "[saying 'you're welcome'] response", "spanish": "De nada / no hay de qué.", "note": "'No hay de qué' is slightly warmer/more Mexican. 'Para servirle' is older/more formal but still heard."},
    {"category": "politeness", "english_context": "[older / more formal 'you're welcome'] response", "spanish": "Para servirle.", "note": "Service workers, older speakers. Charming and respectful — recognize it."},
    {"category": "politeness", "english_context": "[saying 'pleased to meet you'] response", "spanish": "Mucho gusto.", "note": "Standard. Reply: 'igualmente' or 'el gusto es mío'."},
    {"category": "politeness", "english_context": "[response to 'mucho gusto'] response", "spanish": "Igualmente.", "note": "Or 'el gusto es mío' for warmer."},
    {"category": "politeness", "english_context": "[asking 'how are you?' — formal] response", "spanish": "¿Cómo está?", "note": "Usted form. With strangers, service workers older than you, professionals — default to usted in Mexico."},
    {"category": "politeness", "english_context": "[asking 'how are you?' — informal/peer] response", "spanish": "¿Cómo estás? / ¿Cómo te va?", "note": "Tú. Among peers and people who've signaled tú with you."},
    {"category": "politeness", "english_context": "[asking 'how's it going?' — casual] response", "spanish": "¿Cómo te va?", "note": "Slightly more genuine than '¿cómo estás?' which can be perfunctory."},
    {"category": "politeness", "english_context": "[when an older person tells you to use tú with them] response", "spanish": "Háblame de tú.", "note": "Phrase for releasing usted — when said TO you, switch immediately. The opposite request is rare."},
    {"category": "politeness", "english_context": "[switching to formal — what to use with a stranger over 40, doctors, officials, older waiters] response", "spanish": "Usted (use the verb form: ¿usted gusta...?).", "note": "Mexico is MORE usted-prone than many dialects, esp. with older people, in service. Default to usted with anyone you don't know unless they're clearly your age or younger. Better to be too formal than too casual."},
    {"category": "politeness", "english_context": "[older / formal 'would you like...?'] response", "spanish": "¿Gusta usted...?", "note": "Charming Mexican formality. '¿Gusta un cafecito?' = would you care for a coffee? Reverse: don't insist if they decline once."},
    {"category": "politeness", "english_context": "[offering food — 'please, help yourself'] response", "spanish": "Provecho. / Pásele.", "note": "'Buen provecho' said TO others eating ('enjoy'). 'Pásele' = come on in, sit down."},
    {"category": "politeness", "english_context": "[walking past someone eating in a restaurant — Mexican custom] response", "spanish": "Provecho.", "note": "Said in passing to strangers eating. Reply: 'gracias'. Distinctively Mexican courtesy."},
    {"category": "politeness", "english_context": "[Mexican 'God willing / hopefully'] response", "spanish": "Si Dios quiere.", "note": "Sincere usage, not just religious. Tag onto plans: 'mañana voy, si Dios quiere'. Common across all classes."},
    {"category": "politeness", "english_context": "[friend leaving — 'take care of yourself'] response", "spanish": "Que te vaya bien.", "note": "Warm Mexican farewell. Reply: 'gracias, igualmente'."},
    {"category": "politeness", "english_context": "[saying 'thank you very much'] response", "spanish": "Muchas gracias / mil gracias.", "note": "'Mil gracias' is warmer, very Mexican. 'Se lo agradezco' is formal-grateful."},

    # ============================================================
    # MONEY, TIME, NUMBERS IN CONTEXT (~25)
    # ============================================================
    {"category": "money_time", "english_context": "[a 500-peso bill] gloss", "spanish": "Un billete de quinientos.", "note": "Hard to break at small vendors — get smaller bills at OXXO or your bank."},
    {"category": "money_time", "english_context": "[asking 'do you have change for this bill?'] response", "spanish": "¿Tiene cambio?", "note": "Or '¿me cambia este billete?'. 'Cambio' = change (both meanings)."},
    {"category": "money_time", "english_context": "[asking 'can you break this 500?'] response", "spanish": "¿Me cambia este billete de quinientos?", "note": "Many small vendors won't. Plan ahead — break big bills at supermarkets/OXXO."},
    {"category": "money_time", "english_context": "[saying 'I don't have change'] response", "spanish": "No traigo cambio.", "note": "'Traer' = to be carrying on you. Mexicanism vs 'tener'."},
    {"category": "money_time", "english_context": "[asking 'can I pay with card?'] response", "spanish": "¿Puedo pagar con tarjeta?", "note": "Standard. Many small places: cash only."},
    {"category": "money_time", "english_context": "[contactless tap to pay] gloss", "spanish": "Pago sin contacto.", "note": "Increasingly common in CDMX. Tap-to-pay phones widely accepted."},
    {"category": "money_time", "english_context": "[ATM] gloss", "spanish": "El cajero (automático).", "note": "Use bank ATMs (Banorte, BBVA, Santander) rather than free-standing — better rates, lower fees, more secure."},
    {"category": "money_time", "english_context": "[telling time — 'it's 3:15'] response", "spanish": "Son las tres y cuarto.", "note": "Or 'tres quince'. 'Y cuarto / y media / cuarto para las cuatro' standard."},
    {"category": "money_time", "english_context": "[telling time — 'it's a quarter to four'] response", "spanish": "Cuarto para las cuatro.", "note": "Mexican preference. Spain: 'las cuatro menos cuarto'."},
    {"category": "money_time", "english_context": "[asking 'what time is it?'] response", "spanish": "¿Qué hora es? / ¿Me da la hora?", "note": "'Me da la hora' is the polite stranger version."},
    {"category": "money_time", "english_context": "[asking what time something opens/closes] response", "spanish": "¿A qué hora abren / cierran?", "note": "Mexican businesses often close 2-4pm for lunch in smaller cities, less so in CDMX."},
    {"category": "money_time", "english_context": "[saying 'see you in a bit / later'] response", "spanish": "Al rato.", "note": "Vague Mexican 'later'. Like ahorita — could mean an hour or a day."},
    {"category": "money_time", "english_context": "[saying 'right away / immediately'] response", "spanish": "Luego luego.", "note": "TRAP: doubled, it means 'right away'. Single 'luego' means 'later'. Doubling reverses it."},
    {"category": "money_time", "english_context": "[saying 'in a little while'] response", "spanish": "En un rato.", "note": "Slightly more concrete than 'al rato'. Maybe 30min-2hrs."},
    {"category": "money_time", "english_context": "[saying 'the day before yesterday'] response", "spanish": "Antier.", "note": "Mexico uses 'antier'. Spain prefers 'anteayer'. Both understood."},
    {"category": "money_time", "english_context": "[saying 'the day after tomorrow'] response", "spanish": "Pasado mañana.", "note": "Pan-Hispanic."},
    {"category": "money_time", "english_context": "[asking the price total] response", "spanish": "¿Cuánto le debo?", "note": "Polite version of '¿cuánto es?'. Common at restaurants/stalls. 'How much do I owe you?'"},
    {"category": "money_time", "english_context": "[discount appears — 'is that the final price?'] response", "spanish": "¿Ése es el precio final?", "note": "Useful in markets. 'Final' or 'lo último'."},
    {"category": "money_time", "english_context": "[asking how much something costs total with tax] response", "spanish": "¿Ya con IVA?", "note": "'IVA' = sales tax (16%). Restaurants/hotels usually quote tax-included; some businesses don't."},
    {"category": "money_time", "english_context": "[paying — 'keep the change'] response", "spanish": "Quédese con el cambio.", "note": "Common at taxis when rounding up the fare as a small tip."},
    {"category": "money_time", "english_context": "[asking 'how long does it take?'] response", "spanish": "¿Cuánto tarda?", "note": "For travel time, food prep, etc."},
    {"category": "money_time", "english_context": "[asking 'how long have you been waiting?'] response", "spanish": "¿Cuánto lleva esperando?", "note": "'Llevar + gerundio' for ongoing duration."},
    {"category": "money_time", "english_context": "[100 pesos in slang] gloss", "spanish": "Cien varos / un billete.", "note": "'Varo' = peso casually. 'Un billete' colloquially can mean a 100-peso bill or just 'cash'."},
    {"category": "money_time", "english_context": "[20-peso coin/bill — common smallest useful denomination] gloss", "spanish": "Un veinte.", "note": "Useful to know denominations colloquially. Bills: 20, 50, 100, 200, 500, 1000."},
    {"category": "money_time", "english_context": "[end of the workday — 'around 6 in the evening'] response", "spanish": "Como a las seis de la tarde.", "note": "TRAP: 'tarde' extends to ~7-8pm in Mexican usage. 'Noche' starts later than English 'night'."},

    # ============================================================
    # REACTIONS / FILLERS / SOCIAL GLUE (~25)
    # ============================================================
    {"category": "reactions", "english_context": "[agreeing emphatically — 'of course! sure!'] response", "spanish": "¡Claro! / ¡Por supuesto!", "note": "Standard. 'Claro que sí' is even warmer."},
    {"category": "reactions", "english_context": "[agreeing — Mexican 'of course / no problem'] response", "spanish": "¡Cómo no!", "note": "Distinctively warm Mexican affirmative. Almost like 'of course, with pleasure'. NOT a question."},
    {"category": "reactions", "english_context": "[agreeing casually — 'that's right / for sure'] response", "spanish": "Así es.", "note": "Confirms. Common in conversations as a 'yeah, exactly'."},
    {"category": "reactions", "english_context": "[expressing 'wow / no way / really?'] response", "spanish": "¿En serio? / ¡No me digas!", "note": "Standard. Mexican: '¿neta?' is the colloquial version."},
    {"category": "reactions", "english_context": "[showing sympathy — 'oh no / that's awful'] response", "spanish": "¡Qué barbaridad!", "note": "Reaction to bad news/scandal. 'Qué horror' also works."},
    {"category": "reactions", "english_context": "[reacting to a hassle — 'what a pain / what a drag'] response", "spanish": "¡Qué lata!", "note": "Common. 'Lata' = can/tin, idiomatically = nuisance."},
    {"category": "reactions", "english_context": "[reacting to mild frustration — 'aw man'] response", "spanish": "¡Qué oso!", "note": "TRAP: 'qué oso' = 'how embarrassing'. Lit. 'what a bear'. Mexican-specific."},
    {"category": "reactions", "english_context": "[saying you're embarrassed] response", "spanish": "Qué pena / qué oso.", "note": "'Qué pena' = how embarrassing OR how sad/sorry. Context disambiguates."},
    {"category": "reactions", "english_context": "[expressing pity / sympathy] response", "spanish": "Pobrecito / pobrecita.", "note": "'Poor little...'. Diminutive softens. Used for empathy."},
    {"category": "reactions", "english_context": "[Mexican filler — like 'um / well / so'] response", "spanish": "Pues...", "note": "Universal Spanish filler. Mexicans use it constantly. 'Pues sí, pues no, pues bueno'."},
    {"category": "reactions", "english_context": "[Mexican filler — 'like / kinda / so'] response", "spanish": "O sea...", "note": "Filler / clarifier. Like 'I mean'. Used heavily by all ages in Mexico."},
    {"category": "reactions", "english_context": "[hedging an opinion — 'I think / I guess'] response", "spanish": "Pues no sé, ¿no?", "note": "Mexican uptalk-style hedge. 'No?' tag at the end is constant."},
    {"category": "reactions", "english_context": "[soft 'right? / no?' tag at end of statements] response", "spanish": "...¿no?", "note": "Tag question. 'Hace frío, ¿no?'. Mexicans tag almost everything. Standard."},
    {"category": "reactions", "english_context": "[soft 'right?' — alternative tag] response", "spanish": "...¿verdad?", "note": "Like '¿no?' but slightly more inviting agreement. 'Está rico, ¿verdad?'"},
    {"category": "reactions", "english_context": "[asking 'so what?' / 'and?'] response", "spanish": "¿Y qué?", "note": "Casual challenge or 'so what's the upshot?'. Tone matters."},
    {"category": "reactions", "english_context": "[saying 'forget it / never mind'] response", "spanish": "Olvídalo / déjalo así.", "note": "'Déjalo así' = let it be that way."},
    {"category": "reactions", "english_context": "[expressing 'I have no idea'] response", "spanish": "Ni idea.", "note": "Casual. 'No tengo idea' is the full version."},
    {"category": "reactions", "english_context": "[saying 'maybe / who knows'] response", "spanish": "Quién sabe. / Sepa.", "note": "'Sepa' (clipped from 'sepa Dios') is very Mexican for 'beats me'."},
    {"category": "reactions", "english_context": "[saying 'depends'] response", "spanish": "Depende.", "note": "Standalone or 'depende de...'. Common hedge."},
    {"category": "reactions", "english_context": "[ending a story — 'and that was that / end of story'] response", "spanish": "Y ya. / Punto.", "note": "'Y ya' wraps narratives casually. 'Punto' = period, end of discussion."},
    {"category": "reactions", "english_context": "[congratulating someone — 'congrats!'] response", "spanish": "¡Felicidades!", "note": "Birthdays, achievements. '¡Felicitaciones!' also works but 'felicidades' more Mexican."},
    {"category": "reactions", "english_context": "[toast — 'cheers!'] response", "spanish": "¡Salud!", "note": "Drinking toast, AND said when someone sneezes."},
    {"category": "reactions", "english_context": "[saying 'don't worry about it'] response", "spanish": "No te preocupes / no hay problema.", "note": "'No te apures' is the Mexican variant — 'don't fret'."},
    {"category": "reactions", "english_context": "[Mexican 'don't worry / take your time'] response", "spanish": "No te apures.", "note": "Distinctively Mexican over 'no te preocupes'. 'Apurarse' = to rush/worry."},
    {"category": "reactions", "english_context": "[saying it works for you / you're fine with it] response", "spanish": "Está bien / está bueno.", "note": "Both common. 'Está bueno' slightly more colloquial in Mexico."},

    # ============================================================
    # TROUBLE / HEALTH / HELP (~25)
    # ============================================================
    {"category": "trouble", "english_context": "[saying 'I don't feel well'] response", "spanish": "Me siento mal.", "note": "Standard. Specify: 'me siento mareado' (dizzy), 'me duele la cabeza' (headache), 'tengo náuseas'."},
    {"category": "trouble", "english_context": "[saying 'I have a stomachache' — common traveler ailment] response", "spanish": "Me duele el estómago.", "note": "Be specific. 'Estómago' (general) or 'panza' (belly, casual)."},
    {"category": "trouble", "english_context": "[traveler's diarrhea — 'I have diarrhea'] response", "spanish": "Tengo diarrea.", "note": "At pharmacy, this gets you anti-diarrheals over-the-counter. 'Treda' is more colloquial."},
    {"category": "trouble", "english_context": "[asking pharmacist for something for diarrhea] response", "spanish": "¿Tiene algo para la diarrea?", "note": "Pharmacists in Mexico are highly empowered — they'll suggest medications. Loperamida (Imodium) and electrolytes (Suero Vida)."},
    {"category": "trouble", "english_context": "[asking for oral rehydration / electrolyte solution] response", "spanish": "Suero Vida Oral, por favor.", "note": "Brand name everyone uses. Like Pedialyte. Crucial for any stomach issue."},
    {"category": "trouble", "english_context": "[asking if there's a bathroom] response", "spanish": "¿Hay baño? / ¿Dónde está el baño?", "note": "'Baño' covers all uses. 'Sanitarios' on signs. May need to buy something to use it."},
    {"category": "trouble", "english_context": "[asking pharmacist what to take for X] response", "spanish": "¿Qué me recomienda para...?", "note": "Mexican pharmacists give real medical advice. Many pharmacies have a doctor on-site for ~$50 MXN consultation."},
    {"category": "trouble", "english_context": "[pharmacy with on-site doctor] gloss", "spanish": "Farmacia con consultorio.", "note": "Cheap, fast doctor visits attached to pharmacies (Similares, Doctor Simi, etc.). For minor issues, very practical."},
    {"category": "trouble", "english_context": "[saying 'I need a doctor'] response", "spanish": "Necesito un doctor.", "note": "Or 'médico'. For emergencies, hotel front desk can help; for non-emergency, farmacia con consultorio."},
    {"category": "trouble", "english_context": "[saying 'I'm allergic to X'] response", "spanish": "Soy alérgico a... / Soy alérgica a...", "note": "Critical for food/medication. 'Soy alérgico a los mariscos' (shellfish), 'a la penicilina'."},
    {"category": "trouble", "english_context": "[calling for help — emergency] response", "spanish": "¡Ayuda! / ¡Socorro!", "note": "'Auxilio' also. Mexico emergency number: 911."},
    {"category": "trouble", "english_context": "[reporting that something was stolen] response", "spanish": "Me robaron.", "note": "'Me robaron el celular / la cartera'. Past tense, impersonal — they robbed me."},
    {"category": "trouble", "english_context": "[reporting a lost item] response", "spanish": "Se me perdió...", "note": "Reflexive 'se me' diffuses blame ('it got lost on me'). Mexican-natural way to phrase."},
    {"category": "trouble", "english_context": "[asking 'is it safe here?'] response", "spanish": "¿Es seguro por aquí?", "note": "Useful question for hotel staff/locals about specific neighborhoods at specific times."},
    {"category": "trouble", "english_context": "[asking someone to leave you alone] response", "spanish": "Déjeme en paz, por favor.", "note": "Firm but polite. 'No me moleste'. For aggressive vendors/touts/catcallers."},
    {"category": "trouble", "english_context": "[saying you're lost] response", "spanish": "Estoy perdido / perdida.", "note": "Match gender. Then: '¿me puede orientar?'"},
    {"category": "trouble", "english_context": "[asking 'can you help me?'] response", "spanish": "¿Me puede ayudar?", "note": "Polite ask. 'Disculpe, ¿me puede ayudar?'"},
    {"category": "trouble", "english_context": "[saying 'I don't speak Spanish well'] response", "spanish": "No hablo bien español, disculpe.", "note": "Buys patience. Many Mexicans switch to English if they have it; many don't."},
    {"category": "trouble", "english_context": "[asking 'can you speak more slowly?'] response", "spanish": "¿Puede hablar más despacio, por favor?", "note": "'Despacio' = slowly. Very useful early in trip."},
    {"category": "trouble", "english_context": "[asking 'can you repeat that?'] response", "spanish": "¿Me lo repite, por favor?", "note": "Polite. Casual: '¿cómo?' or '¿mande?'"},
    {"category": "trouble", "english_context": "[saying 'I didn't understand'] response", "spanish": "No le entendí.", "note": "TRAP: Mexican Spanish uses 'le' here even though it'd be 'lo' in some other dialects ('no lo entendí' is also fine). Both work."},
    {"category": "trouble", "english_context": "[asking 'what does X mean?'] response", "spanish": "¿Qué quiere decir...?", "note": "Or '¿qué significa...?'. Both fine."},
    {"category": "trouble", "english_context": "[saying 'I left my X at the hotel'] response", "spanish": "Dejé mi... en el hotel.", "note": "'Dejar' = leave behind. Common scenario for forgotten passport, etc."},
    {"category": "trouble", "english_context": "[water safety — asking if water is potable] response", "spanish": "¿El agua es potable / se puede tomar?", "note": "Default answer in Mexico: NO. Stick to bottled. Even ice in dive bars can be tap. Reputable restaurants use purified."},
    {"category": "trouble", "english_context": "[asking if a specific food is safe to eat] response", "spanish": "¿Esto se puede comer sin problema?", "note": "Phrased neutrally. Locals know which stalls are safe. Trust crowded ones."},
]

out_path = Path("/home/claude/dev/deck-augment/out/mx_survival_source.json")

# Validate JSON before writing
serialized = json.dumps(entries, ensure_ascii=False, indent=2)
parsed = json.loads(serialized)
assert len(parsed) == len(entries), "roundtrip mismatch"

out_path.write_text(serialized, encoding="utf-8")

# Stats
from collections import Counter
cats = Counter(e["category"] for e in entries)
print(f"Total: {len(entries)}")
for cat, n in sorted(cats.items()):
    print(f"  {cat}: {n}")
